[package]
name = "portfolio"
version = "0.1.0"
authors = ["lheintzmann1 <lheintzmann1@disroot.org>"]
edition = "2021"

[dependencies]
dioxus = { version = "0.7.1", features = [] }
dioxus-free-icons = { version = "0.10.0", features = ["hero-icons-solid"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

[features]
default = ["web"]
web = ["dioxus/web"]
desktop = ["dioxus/desktop"]
mobile = ["dioxus/mobile"]
